# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = zezin 
ENV POSTGRES_USER = postgres
ENV POSTGRES_PASSWORD = password

# Expose the PostgreSQL port
EXPOSE 5432