version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: zezin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Mude a porta externa para 5433, mas mantenha a interna em 5432

  backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - database
    env_file:
      - .env
